name: my-badges

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  my-badges:
    runs-on: ubuntu-22.04
    steps:
      - name: Update My Badges
        run: npx update-my-badges ${{github.repository_owner}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
